# Generated by Django 5.2.7 on 2025-10-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='columns',
            field=models.PositiveIntegerField(default=1, help_text='Number of columns (seats per row) in the hall.'),
        ),
        migrations.AddField(
            model_name='hall',
            name='rows',
            field=models.PositiveIntegerField(default=1, help_text='Number of rows in the hall for seating.'),
        ),
    ]
