# Generated by Django 5.2.7 on 2025-10-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_hall_columns_hall_rows'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invigilationassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='seatingallocation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hall',
            name='capacity',
        ),
        migrations.AddField(
            model_name='exam',
            name='total_students',
            field=models.PositiveIntegerField(default=0, help_text='The total number of students expected for this exam.'),
        ),
        migrations.AddConstraint(
            model_name='invigilationassignment',
            constraint=models.UniqueConstraint(fields=('exam', 'hall'), name='unique_invigilation_per_hall'),
        ),
        migrations.AddConstraint(
            model_name='seatingallocation',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_student_seat_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='seatingallocation',
            constraint=models.UniqueConstraint(fields=('exam', 'hall', 'seat_number'), name='unique_seat_in_hall_per_exam'),
        ),
    ]
