# Generated by Django 5.2.7 on 2025-10-25 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_attendancerecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date_marked',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('exam', 'student', 'date_marked')},
        ),
    ]
