# Generated by Django 5.2.7 on 2025-10-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_combined',
            field=models.BooleanField(default=False),
        ),
    ]
